kind: Service
apiVersion: v1
metadata:
  name: tarjetatpm-service
  namespace: tarjetas-tpm
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
  selector:
    app: tarjetatpm
